test.assert(jetpack.tabs.focused.contentWindow);
test.assert(jetpack.lib.twitter);
test.assert(jetpack.notifications.show);
test.assert(jetpack.tabs.focused);
test.assert(jetpack.statusBar.append);
test.assert(jetpack.track);
test.assert(jetpack.storage.live);
test.assert(JSON.parse);
test.assert(JSON.stringify);
test.assert(setInterval);
test.assert(clearTimeout);
test.assert(new XMLHttpRequest());
